# Locators of the cloud asset page
select_asset_dashboard = "xpath://div[text()='Cloud Assets']//parent::div[contains(@role,'presentation')]"
dashboard_asset_count = "xpath://div[2][contains(@class,'content-tile')]//div[contains(@class,'value')]"
buisness_unit_button = "xpath://button[@id='btn_filter_pill']//child::span[text()='Business Units']"
cloud_button = "xpath://button[@id='btn_filter_pill']//child::span[text()='Clouds']"
accounts_button = "xpath://button[@id='btn_filter_pill']//child::span[text()='Accounts']"
region_button = "xpath://button[@id='btn_filter_pill']//child::span[text()='Regions']"
advance_filter_button = "xpath://button[@id='btn_advanced_filters']"
advance_search_input_value = "xpath://div[@class='multiselect-wrapper']//child::li[@class='filters-values']"
select_all_checkbox = "xpath://input[@id='chk-all']"
select_values_checkbox = "xpath://div[@class='option-row']//child::label[text()='#']"
apply_button = "xpath://button[@id='btn_apply_filter']"
save_button = "xpath://button[@id='btn_save_filter']"
filter_name_textbox = "xpath://input[@placeholder='Enter Text...']"
save_filter_name_button = "xpath://button[@type='submit' and text()='Save']"
saved_filter_name = "xpath://div[text()='#']"
